# Generated by Django 4.2.9 on 2025-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_remove_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=50, unique=True)),
                ("task_type", models.CharField(max_length=50)),
                ("task_desc", models.CharField(blank=True, max_length=100)),
                ("task_params", models.JSONField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tasks",
                "indexes": [
                    models.Index(fields=["task_type"], name="tasks_task_ty_7bc323_idx"),
                    models.Index(fields=["priority"], name="tasks_priorit_a9efa1_idx"),
                ],
            },
        ),
    ]
