# Generated by Django 4.2.9 on 2025-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("待处理", "待处理"),
                    ("处理中", "处理中"),
                    ("成功", "成功"),
                    ("失败", "失败"),
                    ("重试中", "重试中"),
                    ("已取消", "已取消"),
                ],
                default="待处理",
                max_length=10,
            ),
        ),
    ]
