# Generated by Django 4.2.9 on 2025-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_task_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("task_type", models.CharField(max_length=50)),
                ("task_params", models.JSONField(blank=True, null=True)),
                (
                    "cron_expr",
                    models.CharField(
                        help_text="标准 crontab 表达式：分钟 小时 日 月 星期",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "task_schedules",
                "indexes": [
                    models.Index(
                        fields=["enabled"], name="task_schedu_enabled_46e0fc_idx"
                    ),
                    models.Index(
                        fields=["task_type"], name="task_schedu_task_ty_27b21d_idx"
                    ),
                ],
            },
        ),
    ]
