CREATE VIEW default.stock_fin_v
(
    `code` String,
    `date` Date,
    `CM_NPAS` Float64,
    `CM_TOR` Float64,
    `CM_OC` Float64,
    `CM_NP` Float64,
    `CM_NRNP` Float64,
    `CM_TSE_NA` Float64,
    `CM_GW` Float64,
    `CM_NOCF` Float64,
    `CM_BEPS` Float64,
    `CM_NAPS` Float64,
    `CM_CFPS` Float64,
    `CM_ROE` Float64,
    `CM_ROA` Float64,
    `CM_GM` Float64,
    `CM_NPM` Float64,
    `CM_PER` Float64,
    `CM_ALR` Float64,
    `PSI_BEPS` Float64,
    `PSI_DEPS` Float64,
    `PSI_DEPS_LSC` Float64,
    `PSI_DNAPS_PSC` Float64,
    `PSI_ANAPS_PSC` Float64,
    `PSI_NAPS_LSC` Float64,
    `PSI_OCFPS` Float64,
    `PSI_NCFPS` Float64,
    `PSI_FCFFPS` Float64,
    `PSI_FCFEPS` Float64,
    `PSI_UPPS` Float64,
    `PSI_CRPS` Float64,
    `PSI_SRPS` Float64,
    `PSI_REPS` Float64,
    `PSI_ORPS` Float64,
    `PSI_TORPS` Float64,
    `PSI_EBITPS` Float64,
    `PCP_ROE` Float64,
    `PCP_DROE` Float64,
    `PCP_AROE` Float64,
    `PCP_AROE_ENR` Float64,
    `PCP_DROE_ENR` Float64,
    `PCP_EBITM` Float64,
    `PCP_ROA` Float64,
    `PCP_ROTC` Float64,
    `PCP_ROIC` Float64,
    `PCP_AROAAt_EI` Float64,
    `PCP_GM` Float64,
    `PCP_NPM` Float64,
    `PCP_CEPR` Float64,
    `PCP_OPM` Float64,
    `PCP_ANPMTA` Float64,
    `PCP_ANPMTA_IMI` Float64,
    `GCP_NPAS` Float64,
    `GCP_TOR` Float64,
    `GCP_NP` Float64,
    `GCP_NRNP` Float64,
    `GCP_TORGR` Float64,
    `GCP_GRNPAPC` Float64,
    `EQL_NOCF_SR` Float64,
    `EQL_NOCF_TOR` Float64,
    `EQL_CER` Float64,
    `EQL_PER` Float64,
    `EQL_CSR` Float64,
    `EQL_NOCF_NPAPC` Float64,
    `EQL_IT_TP` Float64,
    `FR_CR` Float64,
    `FR_QR` Float64,
    `FR_CQR` Float64,
    `FR_ALR` Float64,
    `FR_EM` Float64,
    `FR_EM_IMINA` Float64,
    `FR_DER` Float64,
    `FR_CashR` Float64,
    `OCP_ART` Float64,
    `OCP_ARTD` Float64,
    `OCP_IT` Float64,
    `OCP_ITD` Float64,
    `OCP_TAT` Float64,
    `OCP_TATD` Float64,
    `OCP_CAT` Float64,
    `OCP_CATD` Float64,
    `OCP_APT` Float64
)
AS SELECT
    code,
    date,
    argMax(CM_NPAS, _version) AS CM_NPAS,
    argMax(CM_TOR, _version) AS CM_TOR,
    argMax(CM_OC, _version) AS CM_OC,
    argMax(CM_NP, _version) AS CM_NP,
    argMax(CM_NRNP, _version) AS CM_NRNP,
    argMax(CM_TSE_NA, _version) AS CM_TSE_NA,
    argMax(CM_GW, _version) AS CM_GW,
    argMax(CM_NOCF, _version) AS CM_NOCF,
    argMax(CM_BEPS, _version) AS CM_BEPS,
    argMax(CM_NAPS, _version) AS CM_NAPS,
    argMax(CM_CFPS, _version) AS CM_CFPS,
    argMax(CM_ROE, _version) AS CM_ROE,
    argMax(CM_ROA, _version) AS CM_ROA,
    argMax(CM_GM, _version) AS CM_GM,
    argMax(CM_NPM, _version) AS CM_NPM,
    argMax(CM_PER, _version) AS CM_PER,
    argMax(CM_ALR, _version) AS CM_ALR,
    argMax(PSI_BEPS, _version) AS PSI_BEPS,
    argMax(PSI_DEPS, _version) AS PSI_DEPS,
    argMax(PSI_DEPS_LSC, _version) AS PSI_DEPS_LSC,
    argMax(PSI_DNAPS_PSC, _version) AS PSI_DNAPS_PSC,
    argMax(PSI_ANAPS_PSC, _version) AS PSI_ANAPS_PSC,
    argMax(PSI_NAPS_LSC, _version) AS PSI_NAPS_LSC,
    argMax(PSI_OCFPS, _version) AS PSI_OCFPS,
    argMax(PSI_NCFPS, _version) AS PSI_NCFPS,
    argMax(PSI_FCFFPS, _version) AS PSI_FCFFPS,
    argMax(PSI_FCFEPS, _version) AS PSI_FCFEPS,
    argMax(PSI_UPPS, _version) AS PSI_UPPS,
    argMax(PSI_CRPS, _version) AS PSI_CRPS,
    argMax(PSI_SRPS, _version) AS PSI_SRPS,
    argMax(PSI_REPS, _version) AS PSI_REPS,
    argMax(PSI_ORPS, _version) AS PSI_ORPS,
    argMax(PSI_TORPS, _version) AS PSI_TORPS,
    argMax(PSI_EBITPS, _version) AS PSI_EBITPS,
    argMax(PCP_ROE, _version) AS PCP_ROE,
    argMax(PCP_DROE, _version) AS PCP_DROE,
    argMax(PCP_AROE, _version) AS PCP_AROE,
    argMax(PCP_AROE_ENR, _version) AS PCP_AROE_ENR,
    argMax(PCP_DROE_ENR, _version) AS PCP_DROE_ENR,
    argMax(PCP_EBITM, _version) AS PCP_EBITM,
    argMax(PCP_ROA, _version) AS PCP_ROA,
    argMax(PCP_ROTC, _version) AS PCP_ROTC,
    argMax(PCP_ROIC, _version) AS PCP_ROIC,
    argMax(PCP_AROAAt_EI, _version) AS PCP_AROAAt_EI,
    argMax(PCP_GM, _version) AS PCP_GM,
    argMax(PCP_NPM, _version) AS PCP_NPM,
    argMax(PCP_CEPR, _version) AS PCP_CEPR,
    argMax(PCP_OPM, _version) AS PCP_OPM,
    argMax(PCP_ANPMTA, _version) AS PCP_ANPMTA,
    argMax(PCP_ANPMTA_IMI, _version) AS PCP_ANPMTA_IMI,
    argMax(GCP_NPAS, _version) AS GCP_NPAS,
    argMax(GCP_TOR, _version) AS GCP_TOR,
    argMax(GCP_NP, _version) AS GCP_NP,
    argMax(GCP_NRNP, _version) AS GCP_NRNP,
    argMax(GCP_TORGR, _version) AS GCP_TORGR,
    argMax(GCP_GRNPAPC, _version) AS GCP_GRNPAPC,
    argMax(EQL_NOCF_SR, _version) AS EQL_NOCF_SR,
    argMax(EQL_NOCF_TOR, _version) AS EQL_NOCF_TOR,
    argMax(EQL_CER, _version) AS EQL_CER,
    argMax(EQL_PER, _version) AS EQL_PER,
    argMax(EQL_CSR, _version) AS EQL_CSR,
    argMax(EQL_NOCF_NPAPC, _version) AS EQL_NOCF_NPAPC,
    argMax(EQL_IT_TP, _version) AS EQL_IT_TP,
    argMax(FR_CR, _version) AS FR_CR,
    argMax(FR_QR, _version) AS FR_QR,
    argMax(FR_CQR, _version) AS FR_CQR,
    argMax(FR_ALR, _version) AS FR_ALR,
    argMax(FR_EM, _version) AS FR_EM,
    argMax(FR_EM_IMINA, _version) AS FR_EM_IMINA,
    argMax(FR_DER, _version) AS FR_DER,
    argMax(FR_CashR, _version) AS FR_CashR,
    argMax(OCP_ART, _version) AS OCP_ART,
    argMax(OCP_ARTD, _version) AS OCP_ARTD,
    argMax(OCP_IT, _version) AS OCP_IT,
    argMax(OCP_ITD, _version) AS OCP_ITD,
    argMax(OCP_TAT, _version) AS OCP_TAT,
    argMax(OCP_TATD, _version) AS OCP_TATD,
    argMax(OCP_CAT, _version) AS OCP_CAT,
    argMax(OCP_CATD, _version) AS OCP_CATD,
    argMax(OCP_APT, _version) AS OCP_APT
FROM default.stock_fin
GROUP BY
    code,
    date