ATTACH TABLE _ UUID '541ac60d-dd04-4c92-8a9e-c5f58b4eea7f'
(
    `code` String,
    `date` Date,
    `CM_NPAS` Float64 CODEC(ZSTD(1)),
    `CM_TOR` Float64 CODEC(ZSTD(1)),
    `CM_OC` Float64 CODEC(ZSTD(1)),
    `CM_NP` Float64 CODEC(ZSTD(1)),
    `CM_NRNP` Float64 CODEC(ZSTD(1)),
    `CM_TSE_NA` Float64 CODEC(ZSTD(1)),
    `CM_GW` Float64 CODEC(ZSTD(1)),
    `CM_NOCF` Float64 CODEC(ZSTD(1)),
    `CM_BEPS` Float64 CODEC(ZSTD(1)),
    `CM_NAPS` Float64 CODEC(ZSTD(1)),
    `CM_CFPS` Float64 CODEC(ZSTD(1)),
    `CM_ROE` Float64 CODEC(ZSTD(1)),
    `CM_ROA` Float64 CODEC(ZSTD(1)),
    `CM_GM` Float64 CODEC(ZSTD(1)),
    `CM_NPM` Float64 CODEC(ZSTD(1)),
    `CM_PER` Float64 CODEC(ZSTD(1)),
    `CM_ALR` Float64 CODEC(ZSTD(1)),
    `PSI_BEPS` Float64 CODEC(ZSTD(1)),
    `PSI_DEPS` Float64 CODEC(ZSTD(1)),
    `PSI_DEPS_LSC` Float64 CODEC(ZSTD(1)),
    `PSI_DNAPS_PSC` Float64 CODEC(ZSTD(1)),
    `PSI_ANAPS_PSC` Float64 CODEC(ZSTD(1)),
    `PSI_NAPS_LSC` Float64 CODEC(ZSTD(1)),
    `PSI_OCFPS` Float64 CODEC(ZSTD(1)),
    `PSI_NCFPS` Float64 CODEC(ZSTD(1)),
    `PSI_FCFFPS` Float64 CODEC(ZSTD(1)),
    `PSI_FCFEPS` Float64 CODEC(ZSTD(1)),
    `PSI_UPPS` Float64 CODEC(ZSTD(1)),
    `PSI_CRPS` Float64 CODEC(ZSTD(1)),
    `PSI_SRPS` Float64 CODEC(ZSTD(1)),
    `PSI_REPS` Float64 CODEC(ZSTD(1)),
    `PSI_ORPS` Float64 CODEC(ZSTD(1)),
    `PSI_TORPS` Float64 CODEC(ZSTD(1)),
    `PSI_EBITPS` Float64 CODEC(ZSTD(1)),
    `PCP_ROE` Float64 CODEC(ZSTD(1)),
    `PCP_DROE` Float64 CODEC(ZSTD(1)),
    `PCP_AROE` Float64 CODEC(ZSTD(1)),
    `PCP_AROE_ENR` Float64 CODEC(ZSTD(1)),
    `PCP_DROE_ENR` Float64 CODEC(ZSTD(1)),
    `PCP_EBITM` Float64 CODEC(ZSTD(1)),
    `PCP_ROA` Float64 CODEC(ZSTD(1)),
    `PCP_ROTC` Float64 CODEC(ZSTD(1)),
    `PCP_ROIC` Float64 CODEC(ZSTD(1)),
    `PCP_AROAAt_EI` Float64 CODEC(ZSTD(1)),
    `PCP_GM` Float64 CODEC(ZSTD(1)),
    `PCP_NPM` Float64 CODEC(ZSTD(1)),
    `PCP_CEPR` Float64 CODEC(ZSTD(1)),
    `PCP_OPM` Float64 CODEC(ZSTD(1)),
    `PCP_ANPMTA` Float64 CODEC(ZSTD(1)),
    `PCP_ANPMTA_IMI` Float64 CODEC(ZSTD(1)),
    `GCP_NPAS` Float64 CODEC(ZSTD(1)),
    `GCP_TOR` Float64 CODEC(ZSTD(1)),
    `GCP_NP` Float64 CODEC(ZSTD(1)),
    `GCP_NRNP` Float64 CODEC(ZSTD(1)),
    `GCP_TORGR` Float64 CODEC(ZSTD(1)),
    `GCP_GRNPAPC` Float64 CODEC(ZSTD(1)),
    `EQL_NOCF_SR` Float64 CODEC(ZSTD(1)),
    `EQL_NOCF_TOR` Float64 CODEC(ZSTD(1)),
    `EQL_CER` Float64 CODEC(ZSTD(1)),
    `EQL_PER` Float64 CODEC(ZSTD(1)),
    `EQL_CSR` Float64 CODEC(ZSTD(1)),
    `EQL_NOCF_NPAPC` Float64 CODEC(ZSTD(1)),
    `EQL_IT_TP` Float64 CODEC(ZSTD(1)),
    `FR_CR` Float64 CODEC(ZSTD(1)),
    `FR_QR` Float64 CODEC(ZSTD(1)),
    `FR_CQR` Float64 CODEC(ZSTD(1)),
    `FR_ALR` Float64 CODEC(ZSTD(1)),
    `FR_EM` Float64 CODEC(ZSTD(1)),
    `FR_EM_IMINA` Float64 CODEC(ZSTD(1)),
    `FR_DER` Float64 CODEC(ZSTD(1)),
    `FR_CashR` Float64 CODEC(ZSTD(1)),
    `OCP_ART` Float64 CODEC(ZSTD(1)),
    `OCP_ARTD` Float64 CODEC(ZSTD(1)),
    `OCP_IT` Float64 CODEC(ZSTD(1)),
    `OCP_ITD` Float64 CODEC(ZSTD(1)),
    `OCP_TAT` Float64 CODEC(ZSTD(1)),
    `OCP_TATD` Float64 CODEC(ZSTD(1)),
    `OCP_CAT` Float64 CODEC(ZSTD(1)),
    `OCP_CATD` Float64 CODEC(ZSTD(1)),
    `OCP_APT` Float64 CODEC(ZSTD(1)),
    `_version` UInt64 DEFAULT toUnixTimestamp64Nano(now64()) + rowNumberInAllBlocks()
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY toYYYYMM(date)
PRIMARY KEY (code, date)
ORDER BY (code, date)
TTL date + toIntervalYear(15)
SETTINGS index_granularity = 8192
