CREATE VIEW default.stock_data_vv
(
    `code` String,
    `market` String,
    `name` String,
    `sw_first_level` String,
    `sw_second_level` String,
    `sw_third_level` String,
    `price` Float64,
    `hfq` Float64,
    `pe` Float64,
    `pe_ttm` Float64,
    `pb` Float64,
    `dividend_yield` Float64,
    `market_cap` Float64,
    `CM_NPAS` Float64,
    `CM_TOR` Float64,
    `CM_OC` Float64,
    `CM_NP` Float64,
    `CM_NRNP` Float64,
    `CM_TSE_NA` Float64,
    `CM_GW` Float64,
    `CM_NOCF` Float64,
    `CM_BEPS` Float64,
    `CM_NAPS` Float64,
    `CM_CFPS` Float64,
    `CM_ROE` Float64,
    `CM_ROA` Float64,
    `CM_GM` Float64,
    `CM_NPM` Float64,
    `CM_PER` Float64,
    `CM_ALR` Float64,
    `PSI_BEPS` Float64,
    `PSI_DEPS` Float64,
    `PSI_DEPS_LSC` Float64,
    `PSI_DNAPS_PSC` Float64,
    `PSI_ANAPS_PSC` Float64,
    `PSI_NAPS_LSC` Float64,
    `PSI_OCFPS` Float64,
    `PSI_NCFPS` Float64,
    `PSI_FCFFPS` Float64,
    `PSI_FCFEPS` Float64,
    `PSI_UPPS` Float64,
    `PSI_CRPS` Float64,
    `PSI_SRPS` Float64,
    `PSI_REPS` Float64,
    `PSI_ORPS` Float64,
    `PSI_TORPS` Float64,
    `PSI_EBITPS` Float64,
    `PCP_ROE` Float64,
    `PCP_DROE` Float64,
    `PCP_AROE` Float64,
    `PCP_AROE_ENR` Float64,
    `PCP_DROE_ENR` Float64,
    `PCP_EBITM` Float64,
    `PCP_ROA` Float64,
    `PCP_ROTC` Float64,
    `PCP_ROIC` Float64,
    `PCP_AROAAt_EI` Float64,
    `PCP_GM` Float64,
    `PCP_NPM` Float64,
    `PCP_CEPR` Float64,
    `PCP_OPM` Float64,
    `PCP_ANPMTA` Float64,
    `PCP_ANPMTA_IMI` Float64,
    `GCP_NPAS` Float64,
    `GCP_TOR` Float64,
    `GCP_NP` Float64,
    `GCP_NRNP` Float64,
    `GCP_TORGR` Float64,
    `GCP_GRNPAPC` Float64,
    `EQL_NOCF_SR` Float64,
    `EQL_NOCF_TOR` Float64,
    `EQL_CER` Float64,
    `EQL_PER` Float64,
    `EQL_CSR` Float64,
    `EQL_NOCF_NPAPC` Float64,
    `EQL_IT_TP` Float64,
    `FR_CR` Float64,
    `FR_QR` Float64,
    `FR_CQR` Float64,
    `FR_ALR` Float64,
    `FR_EM` Float64,
    `FR_EM_IMINA` Float64,
    `FR_DER` Float64,
    `FR_CashR` Float64,
    `OCP_ART` Float64,
    `OCP_ARTD` Float64,
    `OCP_IT` Float64,
    `OCP_ITD` Float64,
    `OCP_TAT` Float64,
    `OCP_TATD` Float64,
    `OCP_CAT` Float64,
    `OCP_CATD` Float64,
    `OCP_APT` Float64
)
AS SELECT
    fq.code AS code,
    fq.hfq AS hfq,
    sfv.CM_NPAS,
    sfv.CM_TOR,
    sfv.CM_OC,
    sfv.CM_NP,
    sfv.CM_NRNP,
    sfv.CM_TSE_NA,
    sfv.CM_GW,
    sfv.CM_NOCF,
    sfv.CM_BEPS,
    sfv.CM_NAPS,
    sfv.CM_CFPS,
    sfv.CM_ROE,
    sfv.CM_ROA,
    sfv.CM_GM,
    sfv.CM_NPM,
    sfv.CM_PER,
    sfv.CM_ALR,
    sfv.PSI_BEPS,
    sfv.PSI_DEPS,
    sfv.PSI_DEPS_LSC,
    sfv.PSI_DNAPS_PSC,
    sfv.PSI_ANAPS_PSC,
    sfv.PSI_NAPS_LSC,
    sfv.PSI_OCFPS,
    sfv.PSI_NCFPS,
    sfv.PSI_FCFFPS,
    sfv.PSI_FCFEPS,
    sfv.PSI_UPPS,
    sfv.PSI_CRPS,
    sfv.PSI_SRPS,
    sfv.PSI_REPS,
    sfv.PSI_ORPS,
    sfv.PSI_TORPS,
    sfv.PSI_EBITPS,
    sfv.PCP_ROE,
    sfv.PCP_DROE,
    sfv.PCP_AROE,
    sfv.PCP_AROE_ENR,
    sfv.PCP_DROE_ENR,
    sfv.PCP_EBITM,
    sfv.PCP_ROA,
    sfv.PCP_ROTC,
    sfv.PCP_ROIC,
    sfv.PCP_AROAAt_EI,
    sfv.PCP_GM,
    sfv.PCP_NPM,
    sfv.PCP_CEPR,
    sfv.PCP_OPM,
    sfv.PCP_ANPMTA,
    sfv.PCP_ANPMTA_IMI,
    sfv.GCP_NPAS,
    sfv.GCP_TOR,
    sfv.GCP_NP,
    sfv.GCP_NRNP,
    sfv.GCP_TORGR,
    sfv.GCP_GRNPAPC,
    sfv.EQL_NOCF_SR,
    sfv.EQL_NOCF_TOR,
    sfv.EQL_CER,
    sfv.EQL_PER,
    sfv.EQL_CSR,
    sfv.EQL_NOCF_NPAPC,
    sfv.EQL_IT_TP,
    sfv.FR_CR,
    sfv.FR_QR,
    sfv.FR_CQR,
    sfv.FR_ALR,
    sfv.FR_EM,
    sfv.FR_EM_IMINA,
    sfv.FR_DER,
    sfv.FR_CashR,
    sfv.OCP_ART,
    sfv.OCP_ARTD,
    sfv.OCP_IT,
    sfv.OCP_ITD,
    sfv.OCP_TAT,
    sfv.OCP_TATD,
    sfv.OCP_CAT,
    sfv.OCP_CATD,
    sfv.OCP_APT,
    sis.market,
    sis.stock_name AS name,
    sis.sw_first_level,
    sis.sw_second_level,
    sis.sw_third_level,
    sis.price,
    sis.pe,
    sis.pe_ttm,
    sis.pb,
    sis.dividend_yield,
    sis.market_cap
FROM default.fq_factor AS fq
INNER JOIN
(
    SELECT
        code,
        max(date) AS max_date
    FROM default.fq_factor
    GROUP BY code
) AS max_dates ON (fq.code = max_dates.code) AND (fq.date = max_dates.max_date)
INNER JOIN default.stock_fin_v1 AS sfv ON fq.code = sfv.code
INNER JOIN default.sw_industry_stocks_v1 AS sis ON fq.code = sis.code
ORDER BY fq.code ASC