CREATE VIEW default.stock_fin_v1
(
    `code` String,
    `date` Date,
    `CM_NPAS` Float64,
    `CM_TOR` Float64,
    `CM_OC` Float64,
    `CM_NP` Float64,
    `CM_NRNP` Float64,
    `CM_TSE_NA` Float64,
    `CM_GW` Float64,
    `CM_NOCF` Float64,
    `CM_BEPS` Float64,
    `CM_NAPS` Float64,
    `CM_CFPS` Float64,
    `CM_ROE` Float64,
    `CM_ROA` Float64,
    `CM_GM` Float64,
    `CM_NPM` Float64,
    `CM_PER` Float64,
    `CM_ALR` Float64,
    `PSI_BEPS` Float64,
    `PSI_DEPS` Float64,
    `PSI_DEPS_LSC` Float64,
    `PSI_DNAPS_PSC` Float64,
    `PSI_ANAPS_PSC` Float64,
    `PSI_NAPS_LSC` Float64,
    `PSI_OCFPS` Float64,
    `PSI_NCFPS` Float64,
    `PSI_FCFFPS` Float64,
    `PSI_FCFEPS` Float64,
    `PSI_UPPS` Float64,
    `PSI_CRPS` Float64,
    `PSI_SRPS` Float64,
    `PSI_REPS` Float64,
    `PSI_ORPS` Float64,
    `PSI_TORPS` Float64,
    `PSI_EBITPS` Float64,
    `PCP_ROE` Float64,
    `PCP_DROE` Float64,
    `PCP_AROE` Float64,
    `PCP_AROE_ENR` Float64,
    `PCP_DROE_ENR` Float64,
    `PCP_EBITM` Float64,
    `PCP_ROA` Float64,
    `PCP_ROTC` Float64,
    `PCP_ROIC` Float64,
    `PCP_AROAAt_EI` Float64,
    `PCP_GM` Float64,
    `PCP_NPM` Float64,
    `PCP_CEPR` Float64,
    `PCP_OPM` Float64,
    `PCP_ANPMTA` Float64,
    `PCP_ANPMTA_IMI` Float64,
    `GCP_NPAS` Float64,
    `GCP_TOR` Float64,
    `GCP_NP` Float64,
    `GCP_NRNP` Float64,
    `GCP_TORGR` Float64,
    `GCP_GRNPAPC` Float64,
    `EQL_NOCF_SR` Float64,
    `EQL_NOCF_TOR` Float64,
    `EQL_CER` Float64,
    `EQL_PER` Float64,
    `EQL_CSR` Float64,
    `EQL_NOCF_NPAPC` Float64,
    `EQL_IT_TP` Float64,
    `FR_CR` Float64,
    `FR_QR` Float64,
    `FR_CQR` Float64,
    `FR_ALR` Float64,
    `FR_EM` Float64,
    `FR_EM_IMINA` Float64,
    `FR_DER` Float64,
    `FR_CashR` Float64,
    `OCP_ART` Float64,
    `OCP_ARTD` Float64,
    `OCP_IT` Float64,
    `OCP_ITD` Float64,
    `OCP_TAT` Float64,
    `OCP_TATD` Float64,
    `OCP_CAT` Float64,
    `OCP_CATD` Float64,
    `OCP_APT` Float64
)
AS SELECT *
FROM default.stock_fin_v
WHERE (code, date) IN (
    SELECT
        code,
        max(date)
    FROM default.stock_fin_v
    GROUP BY code
)