CREATE TABLE default.sw_index
(
    `IndustryCode` String,
    `date` DateTime,
    `lyrPe` Float64,
    `lyrPeQuantile` Float64,
    `ttmPe` Float64,
    `ttmPeQuantile` Float64,
    `pb` Float64,
    `pbQuantile` Float64,
    `dvRatio` Float64,
    `dvRatioQuantile` Float64,
    `dvTtm` Float64,
    `dvTtmQuantile` Float64,
    `addLyrPe` Float64,
    `addLyrPeQuantile` Float64,
    `addTtmPe` Float64,
    `addTtmPeQuantile` Float64,
    `addPb` Float64,
    `addPbQuantile` Float64,
    `addDvRatio` Float64,
    `addDvTtm` Float64,
    `turnoverRate` Float64,
    `turnoverRateF` Float64,
    `addTurnoverRate` Float64,
    `addTurnoverRateF` Float64,
    `turnoverRateFQuantile` Float64,
    `totalMv` Float64,
    `close` Float64,
    `addClose` Float64,
    `middleLyrPe` Float64,
    `middleLyrPeQuantile` Float64,
    `middleTtmPe` Float64,
    `middleTtmPeQuantile` Float64,
    `middlePb` Float64,
    `middlePbQuantile` Float64,
    `belowNetAssetPercent` Float64,
    `belowNetAssetCount` Int32,
    `total` Int32,
    `value5` String,
    `value10` String,
    `value20` String,
    `value60` String,
    `indexClose` Float64,
    `amount` String,
    `amountCongestion` String,
    `amountCongestionQuantile` Int32,
    `_version` UInt64 DEFAULT toUnixTimestamp64Nano(now64()) + rowNumberInAllBlocks()
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY toYYYYMM(date)
ORDER BY (IndustryCode, date)
TTL date + toIntervalYear(40)
SETTINGS index_granularity = 8192