ATTACH VIEW _ UUID '129032c0-a559-4e2f-b6d9-aa71f8afa26e'
(
    `IndustryCode` String,
    `date` DateTime,
    `lyrPe` Float64,
    `lyrPeQuantile` Float64,
    `ttmPe` Float64,
    `ttmPeQuantile` Float64,
    `pb` Float64,
    `pbQuantile` Float64,
    `dvRatio` Float64,
    `dvRatioQuantile` Float64,
    `dvTtm` Float64,
    `dvTtmQuantile` Float64,
    `addLyrPe` Float64,
    `addLyrPeQuantile` Float64,
    `addTtmPe` Float64,
    `addTtmPeQuantile` Float64,
    `addPb` Float64,
    `addPbQuantile` Float64,
    `addDvRatio` Float64,
    `addDvTtm` Float64,
    `turnoverRate` Float64,
    `turnoverRateF` Float64,
    `addTurnoverRate` Float64,
    `addTurnoverRateF` Float64,
    `turnoverRateFQuantile` Float64,
    `totalMv` Float64,
    `close` Float64,
    `addClose` Float64,
    `middleLyrPe` Float64,
    `middleLyrPeQuantile` Float64,
    `middleTtmPe` Float64,
    `middleTtmPeQuantile` Float64,
    `middlePb` Float64,
    `middlePbQuantile` Float64,
    `belowNetAssetPercent` Float64,
    `belowNetAssetCount` Int32,
    `total` Int32,
    `value5` String,
    `value10` String,
    `value20` String,
    `value60` String,
    `indexClose` Float64,
    `amount` String,
    `amountCongestion` String,
    `amountCongestionQuantile` Int32
)
AS SELECT
    IndustryCode,
    date,
    argMax(lyrPe, _version) AS lyrPe,
    argMax(lyrPeQuantile, _version) AS lyrPeQuantile,
    argMax(ttmPe, _version) AS ttmPe,
    argMax(ttmPeQuantile, _version) AS ttmPeQuantile,
    argMax(pb, _version) AS pb,
    argMax(pbQuantile, _version) AS pbQuantile,
    argMax(dvRatio, _version) AS dvRatio,
    argMax(dvRatioQuantile, _version) AS dvRatioQuantile,
    argMax(dvTtm, _version) AS dvTtm,
    argMax(dvTtmQuantile, _version) AS dvTtmQuantile,
    argMax(addLyrPe, _version) AS addLyrPe,
    argMax(addLyrPeQuantile, _version) AS addLyrPeQuantile,
    argMax(addTtmPe, _version) AS addTtmPe,
    argMax(addTtmPeQuantile, _version) AS addTtmPeQuantile,
    argMax(addPb, _version) AS addPb,
    argMax(addPbQuantile, _version) AS addPbQuantile,
    argMax(addDvRatio, _version) AS addDvRatio,
    argMax(addDvTtm, _version) AS addDvTtm,
    argMax(turnoverRate, _version) AS turnoverRate,
    argMax(turnoverRateF, _version) AS turnoverRateF,
    argMax(addTurnoverRate, _version) AS addTurnoverRate,
    argMax(addTurnoverRateF, _version) AS addTurnoverRateF,
    argMax(turnoverRateFQuantile, _version) AS turnoverRateFQuantile,
    argMax(totalMv, _version) AS totalMv,
    argMax(close, _version) AS close,
    argMax(addClose, _version) AS addClose,
    argMax(middleLyrPe, _version) AS middleLyrPe,
    argMax(middleLyrPeQuantile, _version) AS middleLyrPeQuantile,
    argMax(middleTtmPe, _version) AS middleTtmPe,
    argMax(middleTtmPeQuantile, _version) AS middleTtmPeQuantile,
    argMax(middlePb, _version) AS middlePb,
    argMax(middlePbQuantile, _version) AS middlePbQuantile,
    argMax(belowNetAssetPercent, _version) AS belowNetAssetPercent,
    argMax(belowNetAssetCount, _version) AS belowNetAssetCount,
    argMax(total, _version) AS total,
    argMax(value5, _version) AS value5,
    argMax(value10, _version) AS value10,
    argMax(value20, _version) AS value20,
    argMax(value60, _version) AS value60,
    argMax(indexClose, _version) AS indexClose,
    argMax(amount, _version) AS amount,
    argMax(amountCongestion, _version) AS amountCongestion,
    argMax(amountCongestionQuantile, _version) AS amountCongestionQuantile
FROM default.sw_index
GROUP BY
    IndustryCode,
    date
